### ISSUE TITLE
bad promote_rule

### ISSUE THREAD

**Issue by vtjnash** [mtsch/Ripserer.jl#161]
A promote_rule is not supposed to non-terminating, as that violates the specification of promote_type.
Look at the code here: https://github.com/mtsch/Ripserer.jl/blob/62a369cd0e6e5cb1bdda8848b5959c95d3525cfc/src/base/primefield.jl#L84

There should be an additional rule to resolve the ambiguity there. That looks like:
```julia
Base.promote_rule(::Type{Mod{M}}, ::Type{<:Mod}) where {M} = Union{}
```

Additionally, I noticed that you appear to have assumed that all `Integers` are an `Int`, which is not always true. You can make your current rule more accurate by first checking it the Integer is directly promotable to Int:
```julia
Base.promote_rule(::Type{Mod{M}}, ::Type{N}) where {M, N<:Integer} = Base.promote_type(N, Int) === Int ? Mod{M} : Union{}
```

**Comment by mtsch** [comment]
Thanks for pointing this out! I wasn't aware that was an issue.
