### ISSUE TITLE
slow computation for a custom filtration of depth 1 (simplicial complex)

### ISSUE THREAD

**Issue by lampretl** [mtsch/Ripserer.jl#169]
Ripser(er) computes the persistent homology of point-cloud data, and more generally, of a simplicial filtration. In particular, when the filtration has only 1 level, it computes the ordinary homology of a simplicial complex over a finite field $\mathbb{Z}/p$. 

Ripserer's speed, generally, is very impressive! For example, my triangulation of $\mathbb{RP}^7$ has 14_618_690 simplices, yet its homology over $\mathbb{Z}/p$ is computed in <4sec on my laptop. I wanted to use this functionality. Consider the following code:

```
# triangulation of RP3 and simplicial complex of all non-dominating sets in the torus graph C4□C5
facets1 = [[1,3,5,10], [2,3,7,8], [1,3,7,10], [4,5,6,11], [2,5,7,9], [4,5,7,9], [1,4,8,9], [3,6,9,10], [4,6,7,10], [4,5,6,7], [2,3,4,8], [2,3,4,11], [1,4,7,9], [1,2,6,9], [1,5,8,10], [2,5,9,10], [1,2,3,7], [2,5,8,10], [1,4,7,10], [1,2,7,9], [1,6,8,9], [2,6,9,10], [3,4,8,9], [5,6,7,8], [1,4,8,10], [3,6,7,10], [1,5,6,8], [1,5,6,11], [2,4,8,10], [1,2,6,11], [2,4,6,11], [2,5,7,8], [3,5,9,10], [1,2,3,11], [3,4,5,11], [2,4,6,10], [3,6,8,9], [3,6,7,8], [1,3,5,11], [3,4,5,9]] 
facets2 = [[5,7,4,6,8,10,11,12,13,14,15,17,18,19,20], [3,5,7,9,6,8,12,13,14,15,16,17,18,19,20], [7,9,2,6,8,10,11,12,13,14,15,16,18,19,20], [1,5,7,9,8,10,11,13,14,15,16,17,18,19,20], [1,9,2,4,8,10,11,12,13,14,15,16,17,19,20], [1,3,7,9,2,10,11,12,14,15,16,17,18,19,20], [1,3,2,4,6,10,11,12,13,14,15,16,17,18,20], [1,3,5,9,2,4,11,12,13,15,16,17,18,19,20], [3,5,2,4,6,8,11,12,13,14,15,16,17,18,19], [1,3,5,7,4,6,11,12,13,14,16,17,18,19,20], [1,3,5,7,9,4,6,8,10,13,14,17,18,19,20], [1,3,5,7,9,2,6,8,10,14,15,16,18,19,20], [1,3,5,7,9,2,4,8,10,11,15,16,17,19,20], [1,3,5,7,9,2,4,6,10,11,12,16,17,18,20], [1,3,5,7,9,2,4,6,8,12,13,16,17,18,19], [3,5,7,9,2,4,6,8,10,12,13,14,15,18,19], [1,5,7,9,2,4,6,8,10,11,13,14,15,19,20], [1,3,7,9,2,4,6,8,10,11,12,14,15,16,20], [1,3,5,9,2,4,6,8,10,11,12,13,15,16,17], [1,3,5,7,2,4,6,8,10,11,12,13,14,17,18]]  

for fct ∈ (facets1, facets2)
    @time flt = Ripserer.Custom([Tuple(σ)=>1 for σ∈fct]; threshold=1)  # filtration with 1 level
    @time dgm = Ripserer.ripserer(flt, reps=true, dim_max=maximum(length(σ) for σ∈fct)-1, modulus=2, verbose=true)  # persistence diagram (homology)
    for h∈dgm  display(h); end
end
```
Computing the PH of the first complex immediately gives the result. However, for the second, over 2 days have passed and `flt` hasn't even been created, even though the number of simplices is 382_844, and in each dimension, the number of simplices is not too large:
`[20, 190, 1140, 4845, 15444, 37250, 66420, 85865, 80080, 53960, 26200, 9010, 2100, 300, 20]`

Am I doing something wrong or suboptimal, or is this currently a weak spot of Ripserer? (simplicial complex that consists of a small number of facets, but those are high-dimensional)

**Comment by mtsch** [comment]
O, bivši asistent! 

Thanks for the report, it definitely shouldn't be taking this long. It turns out that the way I was adding simplices and their facets to a `Custom` filtration was a bit silly. This worked fine for low-dimensional simplices, which was mostly what I've been testing, but exploded for anything a bit higher.

Another thing to keep in mind here is that with high dimensions, your simplex indices may get very large. If you get weird errors (e.g. something trying to compute the square root of a negative number) when running the code, use `Custom{Int128}`.

**Comment by lampretl** [comment]
Hehe, zgleda sm te uču. Lepo d si sprogramiral ta package! :)

Thank you for the nice improvement. With the latest commit, the second example needs less than 1sec to finish. 

When will you release an official new version of the package? The last time this happened was in 2022.
