### ISSUE TITLE
[JOSS] Add section to the README and DOCS about related efforts in Julia

### ISSUE THREAD

**Issue by juliohm** [mtsch/Ripserer.jl#94]
Thank you @mtsch for this great package. Could you please add a section with that comparison you shared on Discourse?

https://discourse.julialang.org/t/ann-ripserer-efficient-persistent-homology-computation-in-julia/40639/4

**Comment by mtsch** [comment]
Great idea, thanks! I added the section to the docs. I'd rather not have it in the README. I'd like to keep it minimalistic.

**Comment by juliohm** [comment]
Awesome! I will start the review after the editor clarifies the checklist on that JOSS thread :+1: 

I don't think we will need many changes, you did a great job. Closing this one.
